config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	 before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index 
  	@tasks = Task.all
  end

  def new
  	@task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def show
  end

  def update
  	@task.update(task_params)
  	redirect_to tasks_path
  end

  def destroy
  	@task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for (@task) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>
<%= link_to 'Delete', task_path(@task.id), method: :delete  %>

app/views/tasks/index.html.erb
<ol>
	<% @tasks.each do |task| %>
	<li><%= link_to task.name, task_path(task) %></li>
	<% end %>
</ol>

app/views/tasks/new.html.erb
<h1>New Task:</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Name: <%= @task.name %></h1>
<h2>Description <%= @task.details %></h2>

<%= link_to "Edit", edit_task_path(@task.id) %>